version: '3'
services:
    nginx:
        image: nginx:latest
        # 端口映射
        ports:
            - "81:80"
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            # 映射主机./conf.d目录到容器/etc/nginx/conf.d目录
            - "$PWD/conf.d:/etc/nginx/conf.d"
            - "$PWD/html:/usr/share/nginx/html"
        networks:
            - app_net
        # 容器名称
        container_name: "compose-nginx"
    php:
        build: ./php-mysqli
        image: php:7.2-fpm-mysqli
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/html:/var/www/html"
        networks:
            - app_net
        container_name: "compose-php"
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        # 环境变量
        environment:
            # mysql密码
            - MYSQL_ROOT_PASSWORD=123456
        container_name: "compose-mysql"
    redis:
        # 指定镜像
        image: redis:latest
        ports:
          # 端口映射
          - 6379:6379

    mongo:
        image: mongo
        restart: always
        ports:
          - 27017:27017
    
    memcached:
        image: memcached
        restart: always
        ports:
          - 11211:11211
networks:
    # 配置docker network
    app_net:
        driver: bridge
        ipam:
            config:
                # 子网络
                - subnet: 10.10.0.0/16

